FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux go build -o client -trimpath cmd/client/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /app
COPY --from=build /app/client .
ENTRYPOINT ["/app/client"]